In [1]:
import numpy as np

In [2]:
# Q1: Create a 3x3 matrix from 1-9
mat = np.arange(1, 10).reshape(3, 3)
print("3x3 matrix:\n", mat)

3x3 matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# Q2: Calculate mean and std
print("Mean:", mat.mean())
print("Std Dev:", mat.std())

Mean: 5.0
Std Dev: 2.581988897471611


In [4]:
# Q3: Flatten and multiply
flat = mat.flatten() * 3
print("Flattened * 3:", flat)

Flattened * 3: [ 3  6  9 12 15 18 21 24 27]


In [5]:
# Q4: Random numbers & percentile
rand_nums = np.random.randn(1000)
print("95th Percentile:", np.percentile(rand_nums, 95))

95th Percentile: 1.571999185442993


In [6]:
# Q5: Broadcasting example
base = np.ones((3, 3))
row = np.array([1, 2, 3])
print("Broadcasted result:\n", base + row)

Broadcasted result:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
