In [1]:
# 🛠️ Real-World Use Cases with NumPy

In [2]:
# 1. Image Filter (mocked as 2D data)
import numpy as np
from matplotlib import pyplot as plt

image = np.random.rand(5, 5)
kernel = np.array([[0, -1, 0], [-1, 5,-1], [0, -1, 0]])

def apply_filter(image, kernel):
    from scipy.signal import convolve2d
    return convolve2d(image, kernel, mode='same')

filtered = apply_filter(image, kernel)
print("Filtered image:\n", filtered)

Filtered image:
 [[ 2.16002402  0.51393858  0.28855921  1.47863514  3.6700625 ]
 [ 1.73009635  0.1153501  -0.54856619  0.1004366   0.94083988]
 [-0.37716758  1.77958856  0.09792178  0.97747751 -0.18165605]
 [ 2.55685623  1.43337752 -1.78732547  2.06838922  0.36605849]
 [-0.66092668  3.90785283 -1.48428525  1.09051161  3.02657516]]


In [3]:
# 2. Monte Carlo Simulation (Estimate Pi)
np.random.seed(0)
inside_circle = 0
total = 10000

for _ in range(total):
    x, y = np.random.rand(2)
    if x**2 + y**2 <= 1:
        inside_circle += 1

pi_estimate = (inside_circle / total) * 4
print("Estimated Pi:", pi_estimate)


Estimated Pi: 3.1552


In [4]:
# 3. Matrix Gradebook App
grades = np.array([[87, 90, 78], [85, 88, 92], [70, 60, 90]])
averages = grades.mean(axis=1)
print("Student Averages:", averages)

Student Averages: [85.         88.33333333 73.33333333]
