In [3]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])
print("Array a:", a)
print("Array b:\n", b)

Array a: [1 2 3]
Array b:
 [[1 2]
 [3 4]]


In [4]:
print("Shape of b:", b.shape)
print("Data type:", b.dtype)

Shape of b: (2, 2)
Data type: int32


In [5]:
zeros = np.zeros((2, 3))

In [7]:
ones = np.ones((3,))

In [8]:
identity = np.eye(3)

In [10]:
full = np.full((2, 2), 7)

In [9]:
arange = np.arange(0, 10, 2)

In [11]:
linspace = np.linspace(0, 1, 5)

In [12]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])           # Slicing
print(arr[-1])            # Last element
print(arr[arr > 20])      # Boolean indexing

[20 30 40]
50
[30 40 50]


In [13]:
reshaped = np.arange(9).reshape(3, 3)
print("Reshaped:\n", reshaped)

Reshaped:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print("Add:", x + y)
print("Multiply:", x * y)
print("Dot:", np.dot(x, y))

Add: [5 7 9]
Multiply: [ 4 10 18]
Dot: 32
